@Webhook.API_HostAddress = http://localhost:5101

### Create Order
POST {{Webhook.API_HostAddress}}/orders
Content-Type : application/json

{
    "CustomerName":"ilhan enes daniþ",
    "Amount":500
}


### Create Subsription
POST {{Webhook.API_HostAddress}}/webhooks/subsriptions
Content-Type : application/json
{
    "WebhokUrl":"https://webhook.site/ad609596-ad61-4edd-8cf2-eb9d7256a2b4",
    "EventType":"order.created"
}